### PR TITLE
No need to make

### PR DESCRIPTION
**Pull request by viktorbenei**
go get can download the source & `go install` it in a single command!

### CODE REVIEW

**Comment by viktorbenei** [comment]
This is the standard way of installing go tools, see https://github.com/tools/godep#install for example.

**Comment by huytd** [comment]
Thank you so much! 👍 @viktorbenei

**Comment by huytd** [comment]
Honestly, I didn't know this before 😅 thank you!!!

**Comment by viktorbenei** [comment]
Yeah, it's something not that obvious, until you come across a couple of Go CLI tools which use this install method 😉

That said I wonder whether we should remove the `-u` flag. Personally I prefer to use `-u`, as that gets the latest version of the package even if the package (an older version) is available locally, but most popular tool install guides don't include the `-u` flag.

IMO not including `-u` can be important if the package can be used as a Go package in your projects, but for tools `-u` makes the `go get` command to serve both as an initial install, as well as an upgrade command (if you already have the tool, `-u` will get the latest version, while without `-u` it won't).

What do you think?

Another thing I'd add is the `-v` flag (e.g. https://github.com/spf13/cobra#installing). The verbose output of `go get` is not terribly verbose, an on the other hand it helps to track the progress.

If you agree I'll add the `-v` flag in a separate PR, but I'd wait for your response regarding `-u` first, to do the changes in one PR (if you'd decide to drop `-u`).

**Comment by viktorbenei** [comment]
anyway, created a PR with this change - https://github.com/huytd/go-play/pull/18
if you'd rather remove the `-u` flag just let me know ;)

**Pull request merged**
